Now extras.py = default.py & FOLDER_ID YaGPT API KEY gets info from config.py in app & default.py is dependant on config.py
shampsdev/kvizik-backend pull request #2
Opened 2024-09-19 19:47 UTC by plugg1N

https://app.weeek.net/ws/644760/task/15

2024-09-19 20:52 UTC, AlexDyakonov requested changes

2024-09-19 20:52 UTC, AlexDyakonov commented on app/config.py
> +YA_GPT_API_KEY = os.environ["YA_GPT_KEY_API"]
Добавь валидацию (если вдруг что-то не дано)

2024-09-19 20:52 UTC, AlexDyakonov commented on app/ml-pipeline/default.py
> +    "Authorization": f"Api-Key {YA_GPT_API_KEY}"
Проблема в том, что ты создаешь лишнюю зависимость. Не надо сюда прокидывать енву из конфига
Выходит, что для настройки модуля, нам придется залезть в какой-то блок внутри модуля и настраивать его.

2024-09-19 20:52 UTC, AlexDyakonov commented on app/config.py
> +YA_GPT_API_KEY = os.environ["YA_GPT_KEY_API"]
Советую подключить логгер (можно использовать дефолтный питоновский, позже сконфигурируем его)

2024-09-19 20:52 UTC, AlexDyakonov commented on app/ml-pipeline/default.py
> +    "Authorization": f"Api-Key {YA_GPT_API_KEY}"
Конфигурация модуля должна быть в самом модуле, а не в его файлах. Это тут:
`app/ml-pipeline/AITestGenerator.py`

2024-10-09 21:15 UTC, Vaniog commented
Вмёржду, исправим, когда будем конфиг через pydantic делать. Вроде планируется

2024-11-20 23:54 UTC, closed without merging